Churakov_L3
Student-MAD/android-homeworks pull request #1
Opened 2021-10-27 11:07 UTC by DyreLosh

Added transitions between Activity

2021-11-08 18:43 UTC, MegaR1CK requested changes
Переименуй некоторые рисунки согласно п. 7 руководства, не все соответствуют
В xml разметке не все id соответствуют п.2 руководства
И на эмуляторе (Pixel XL) экраны немного уезжают под навбар, попробуй задать верхние паддинги поменьше. Можно было бы сделать скроллящийся экран, но это еще рано.

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/LoginActivity.kt
> +            if (validate.validateEmail(email) == null &&
можно проверять error у поля, а не вызывать методы по второму разу

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/ProfileActivity.kt
> +class ProfileActivity : AppCompatActivity() {
Нужно передавать в активность почту пользователя и отображать ее через строку с параметром

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +            if (validate.validateName(username) == null && validate.validateEmail(email) == null &&
Аналогично тому, что в Login

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +
Пустые строки можно не оставлять

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +            if (validate.validateName(username) == null && validate.validateEmail(email) == null &&
И перенеси второе условие на новую строку, чтобы каждое условие было на своей строке

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/validation/Validation.kt
> +
Пустую строку убрать

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/validation/Variable.kt
> +enum class VariableLength(lenght: Int) {
Если не используешь enum, удали их

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/validation/Validation.kt
> +class Validation(private val context: Context) {
Validator (руководство п. 5)

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_profile.xml
> +            tools:ignore="RtlHardcoded" />
Убери везде игноры

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/values/strings.xml
> +    <string name="we_help_you_meet_up_you_tasks_on_time">We help you meet up you tasks on time</string>
Некоторые строки не соответствуют п. 9 руководства

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/values/styles.xml
> +<resources>
Если умеешь пользоваться стилями, почему бы не сделать подобное для инпутов?

2021-11-08 18:43 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +            username.error = validate.validateName(username)
ошибки нужно задавать textinputLayout, а не edittext, чтобы они полноценно отображались

2021-11-09 16:42 UTC, MegaR1CK requested changes
![image](https://user-images.githubusercontent.com/51877618/140966822-fd74b767-5870-477a-9102-0585884c2d47.png)
Отступ сверху на регистрации вообще можно 20-30 сделать

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +        val email = binding.editTextEmail
Если используешь значение один раз, можно не выносить в переменную

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/RegisterActivity.kt
> +                intent.putExtra("name", "Welcome ${username.text}")
В ресурсы, нужно использовать строку с параметром из ресурсов

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/yellow_design_left"
Поменять id

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/yellow_design_top"
Тоже

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/loginAct_image"
Тоже

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/imageView"
Задать корректные id в этом файле, даже если не используются в коде. Либо задаешь корректно, либо вообще не задаешь

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_profile.xml
> +        android:id="@+id/frameLayout"
Также

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_register.xml
> +        android:id="@+id/imageView6"
Также

2021-11-09 16:42 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/res/layout/activity_register.xml
> +            android:inputType="textVisiblePassword"/>
Зачем visiblePassword?

2021-11-09 19:12 UTC, MegaR1CK approved these changes

2021-11-10 10:25 UTC, Alexandr-Prokin approved these changes

2021-11-10 10:28 UTC, merged