Guznova L4
Student-MAD/android-homeworks pull request #11
Opened 2021-11-19 17:30 UTC by NastenkaG

2021-11-26 09:05 UTC, MegaR1CK requested changes

2021-11-26 09:05 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/ProfileFragment.kt
> +class ProfileFragment() : Fragment() {
Скобочки при пустом конструкторе твоего класса необязательны, везде поправить

2021-11-26 09:05 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/ProfileFragment.kt
> +        binding.iconExit.setOnClickListener() {
У листенера то же самое

2021-11-26 09:05 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/FragmentTaskList.kt
> +class FragmentTaskList : Fragment() {
Некорректное именование

2021-11-26 09:09 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/HomeActivity.kt
> +                    true
Возвращение true можно вынести за when, тут все ветви одно возвращают

2021-12-03 08:28 UTC, MegaR1CK approved these changes

2021-12-03 10:02 UTC, Alexandr-Prokin approved these changes

2021-12-04 10:54 UTC, merged