Saltykov_L4
Student-MAD/android-homeworks pull request #12
Opened 2021-11-19 18:41 UTC by IvanSaltykov

2021-11-23 18:37 UTC, MegaR1CK requested changes

2021-11-23 18:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/menu/bottom_navigation_profile.xml
> +        android:id="@+id/menufragmentprofile"
camelCase

2021-11-23 18:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/ProfileActivity.kt
> +                    true
Если везде true, можно вынести из when

2021-11-24 18:13 UTC, Alexandr-Prokin approved these changes

2021-11-26 08:41 UTC, MegaR1CK requested changes
Все норм, но символы паролей не скрываются в точки, сделай так на логине и на регистрации в пароле и подтверждении
inputType password у EditText

2021-11-26 11:43 UTC, MegaR1CK approved these changes

2021-11-26 11:43 UTC, merged