Churakov-L5
Student-MAD/android-homeworks pull request #13
Opened 2021-11-21 13:56 UTC by DyreLosh

Add Toolbar and ViewPager

2021-11-26 08:56 UTC, MegaR1CK requested changes
1. Выполни вход
2. Перейди на профиль
3. И обратно на tasks
Попробуй сам разобраться, в чем проблема

И убери лишние скобки у конструкторов, где они есть

2021-11-26 08:56 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/viewHolderAdapter/MyPagerAdapter.kt
> +package com.example.design_log
Поправь имя пакета

2021-12-03 08:19 UTC, MegaR1CK approved these changes

2021-12-03 10:47 UTC, Alexandr-Prokin approved these changes

2021-12-04 10:54 UTC, merged