app_L5
Student-MAD/android-homeworks pull request #14
Opened 2021-12-01 19:55 UTC by IvanSaltykov

2021-12-03 08:26 UTC, MegaR1CK requested changes

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/TasksFragment.kt
> +class PagerAdapterTasks(tasks_fragment: TasksFragment) : FragmentStateAdapter(tasks_fragment) {
В отдельный файл

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_categories.xml
> +        android:id="@+id/textViewCategorie"/>
categories, и id строки поменяй

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_profile.xml
> +            app:expandedTitleGravity="center_horizontal|bottom">
У тебя это и в стиле, и здесь, давай где-нибудь убери

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_profile.xml
> +                <androidx.constraintlayout.widget.ConstraintLayout
Пустые строки между элементами

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_profile.xml
> +            <TextView
Текст повыше

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_profile.xml
> +            <TextView
убери marginTop

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_profile.xml
> +            android:id="@+id/collapsToolbarProfile"
collapsing

2021-12-03 08:26 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/fragment_categories.xml
> +        android:id="@+id/textViewCategorie"/>
И в других местах

2021-12-07 17:44 UTC, MegaR1CK approved these changes

2021-12-08 10:16 UTC, Alexandr-Prokin requested changes
![image](https://user-images.githubusercontent.com/35171601/145190782-589f265d-5793-4694-9a83-d760776f71e8.png)
Надо что бы текст уместился на экране

2021-12-08 21:21 UTC, Alexandr-Prokin approved these changes

2021-12-10 19:31 UTC, merged