Vlasenkova-L5
Student-MAD/android-homeworks pull request #16
Opened 2021-12-11 05:31 UTC by nastyavlass

задание 5

2021-12-14 18:26 UTC, MegaR1CK requested changes
1. Табов нет
![image](https://user-images.githubusercontent.com/51877618/146057687-5a1f70eb-628e-4d0c-bb8f-98f8cc406b66.png)
2. Что-то не то с тулбаром
3. Войти, на tasks fragment и обратно по боттомнаву и внимание на приветствие

2021-12-14 18:26 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerAdapter.kt
> +            else -> return PagerFragment(5)
Почему 5?

2021-12-14 18:26 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerAdapter.kt
> +            else -> return PagerFragment(5)
и можно вынести return за when

2021-12-14 18:34 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerAdapter.kt
> +            else -> return PagerFragment(5)
И зачем вообще when? Ты же просто создаешь фрагмент с позицией

2022-01-09 13:15 UTC, Alexandr-Prokin commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/ProfileHomeFragment.kt
> +        binding.toolbarHome.title = getString(R.string.home_title, email)
в email ничего не передается, когда отправляешь intent его необходимо получать

2022-02-01 20:35 UTC, MegaR1CK requested changes
Табы есть, но не работают
И убери везде комментированный код

2022-02-02 11:26 UTC, Alexandr-Prokin approved these changes

2022-02-15 16:49 UTC, MegaR1CK approved these changes

2022-02-15 16:49 UTC, merged