Guznova-L5
Student-MAD/android-homeworks pull request #17
Opened 2021-12-11 16:38 UTC by NastenkaG

2021-12-14 18:36 UTC, MegaR1CK requested changes
1. Табов нет
2. Тулбар уезжает вообще полностью
3. Войти, на tasks fragment и обратно по боттомнаву и внимание на приветствие

2021-12-14 18:36 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/FragmentPager.kt
> +class FragmentPager(private val position: Int) : Fragment() {
Наоборот PagerFragment

2021-12-14 18:36 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +        when (position) {
Зачем when? Можно же просто FragmentPager(position)

2022-01-09 12:59 UTC, Alexandr-Prokin reviewed
![image](https://user-images.githubusercontent.com/35171601/148683100-593aef91-62b1-4ef6-8303-2dcb9843e39c.png)
Полностью скрывается, так не должно быть

2022-02-01 20:31 UTC, MegaR1CK approved these changes

2022-02-02 12:00 UTC, Alexandr-Prokin approved these changes

2022-02-02 12:01 UTC, merged