Saltykov L6
Student-MAD/android-homeworks pull request #18
Opened 2021-12-14 19:05 UTC by IvanSaltykov

2021-12-14 20:57 UTC, MegaR1CK requested changes
Пока только код посмотрел, возможно еще будут правки по ui

2021-12-14 20:57 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +        Task("Have Lunch by 1pm1234567890", "23:12 20.06.2021", false),
Не, так не пойдет, давай дату и время хранить в LocalDateTime и парсить в строку только при назначении вьюхе

2021-12-14 20:57 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/Task.kt
> +    var nametask: String,
почему var?

2021-12-14 20:57 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/Task.kt
> +    var nametask: String,
и именование неправильное

2021-12-22 22:08 UTC, MegaR1CK requested changes

2021-12-22 22:08 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/Task.kt
> +    val timeGenerationTask: String,
Ты так и не понял, дату храним в LocalDateTime, а не в String

2021-12-22 22:08 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +    val datetime3 = LocalDateTime.of(2021, 10, 9, 23,23)
Почему такие имена? И нужны ли тут вообще переменные?

2022-01-09 12:49 UTC, Alexandr-Prokin approved these changes
Все хорошо

2022-01-13 13:52 UTC, MegaR1CK requested changes

2022-01-13 13:52 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +    var adapter = TasksAdapter()
Почему var?

2022-01-13 13:52 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +//        var adapter = TasksAdapter()
Убери везде комментированный код, он не должен входить в итоговый вариант

2022-01-13 18:00 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/ProfileFragment.kt
> +    val REQUEST_CODE = 100
это константа, так что давай в companion object, он принадлежит классу в целом, а не экземпляру класса, и пометь как константу

2022-01-13 18:22 UTC, MegaR1CK approved these changes

2022-01-13 18:51 UTC, merged