Ivan Saltykov
Student-MAD/android-homeworks pull request #2
Opened 2021-10-27 18:41 UTC by IvanSaltykov

Верстка + валидация + переходы

2021-11-01 18:36 UTC, MegaR1CK requested changes

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/LoginActivity.kt
> +    val validator = Validator()
В метод

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/PrifileActivity.kt
> +        binding.TVName.text = "Welcome $name"
В ресурсы в строку с параметром

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/PrifileActivity.kt
> +        var name = intent.extras?.getString("Name")
Зачем var?

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +    var validator = Validator()
В метод

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/MainGetStartedActivity.kt
> +class MainGetStartedActivity : AppCompatActivity() {
Просто GetStarted

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/PrifileActivity.kt
> +class PrifileActivity : AppCompatActivity() {
Profile

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +                (!(binding.EditTextRegisterName.text.toString().isEmpty()))
Валидацию имени тоже в класс

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +        var result = false
можно просто возвращать значение условия, без извращений с переменными, везде

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +        var result = false
return userPassword.length >= 8

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +class Validator {
Для каждой ошибки свой текст, возвращай из методов не логические переменные, а строки и задавай их инпутам. Для доступа к ресурсам можно передать в конструктор класса контекст

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/imageView3"
Некорректное именование Id (п. 2 руководства по неймингу)

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/imageView3"
Везде

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:layout_width="306dp"
Не задавать четкие размеры, используй wrap content и match parent, подгоняй марджинами и паддингами

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintHorizontal_bias="0.504"
Биасы убрать везде

2021-11-01 18:36 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus praesent purus tincidunt ut cursus vitae. Nisl, vitae nulla lectus tortor, est a aliquam. Pretium netus"
В ресурсы, все везде

2021-11-03 19:37 UTC, MegaR1CK requested changes

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/LoginActivity.kt
> +                    binding.textViewSingInActivityErrorEmail.visibility = View.VISIBLE
ошибку ставить прямо в поле через error, не надо отдельным элементом

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +                if (!validator.checkEmail(userEmail))
То же самое

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/textViewSingInActivityGreeting"
Можно в Id слово Activity не добавлять

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +    <EditText
TextInputLayout + TextInputEditText, см. мой проект

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +    <EditText
Ну или другие пулл реквесты

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintHorizontal_bias="0.0"
Биасы убрать везде

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:textColor="#000000"
Через ресурсы

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="650dp"
Задай корректную привязку к верхнему элементу

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +        android:layout_height="589dp"
Почему высота явно задана?

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +        android:background="#FFEB3B"
В ресурсы

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_register.xml
> +        android:text="Register"
В ресурсы, везде

2021-11-03 19:37 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/values/strings.xml
> +    <string name="TextView_SingInActivity_Greeting">Welcome Back!</string>
Не нужно указывать тип элемента в строках. И еще раз внимательно прочитай п. 9 руководства

2021-11-08 10:14 UTC, IvanSaltykov commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="650dp"
не понял в каком смысле корректную

2021-11-08 10:16 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="650dp"
К верхнему вью, а не к родителю

2021-11-08 18:52 UTC, MegaR1CK requested changes

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/LoginActivity.kt
> +            if ((validator.checkPassword(userPassword) == null)
Можно через when

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/PrifileActivity.kt
> +class PrifileActivity : AppCompatActivity() {
Переименуй наконец, вроде несложно это сделать

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +            if ((validator.checkPassword(userPassword) == null) and
Особенно через when

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +                    binding.editTextRegisterEmail.error = validator.checkEmail(userEmail)
error нужно задавать textinputlayout, чтобы ошибка нормально отображалась

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +        var result: String? = null
return if (...) string else null

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +        var result: String? = null
Везде

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:layout_marginTop="600dp"
Кнопку привязать к вью выше, а не к контейнеру

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:layout_marginTop="600dp"
Во всех местах так

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +        android:layout_marginTop="600dp"
Соединяй везде view между собой, а не с контейнером

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_login.xml
> +
Пустые строки

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        />
Везде на предыдущую строку

2021-11-08 18:52 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Зачем вложенность?

2021-11-11 17:56 UTC, MegaR1CK requested changes

2021-11-11 17:56 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/LoginActivity.kt
> +            if (validator.checkPassword(userPassword) == null &&
Не прогоняем методы 2 раза, проверяем ошибку инпута

2021-11-11 17:56 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +            if (validator.checkPassword(userPassword) == null &&
Аналогично

2021-11-11 17:56 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +        return if (userName.isEmpty())
Имя больше 4 символов

2021-11-11 17:56 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/Validator.kt
> +            context.getString(R.string.error_confirmpassword)
Поле подтверждения не проверяется на пустоту

2021-11-11 18:05 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/java/com/example/app/RegisterActivity.kt
> +package com.example.app
![изображение](https://user-images.githubusercontent.com/35171601/141347148-8d53095e-0e57-43ff-a8d1-ae3ab83332c0.png)
нужно уменьшить верхний отступ, проверь еще экран регистрации

2021-11-14 16:24 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_register.xml
> +        android:text="@string/registe_button"
register

2021-11-14 16:57 UTC, Alexandr-Prokin approved these changes

2021-11-14 17:08 UTC, MegaR1CK approved these changes

2021-11-14 17:24 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_main.xml
> +        android:paddingTop="30dp"
Сделай padding в соответствии с дизайном 
![image](https://user-images.githubusercontent.com/35171601/141691490-7eeb3033-e1e5-4538-b0d6-f97784cd17f8.png)

2021-11-14 17:28 UTC, MegaR1CK requested changes
.

2021-11-14 19:53 UTC, MegaR1CK requested changes

2021-11-14 19:53 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +            android:contentDescription=""
или назначь, или убери

2021-11-14 19:53 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +            android:src="@drawable/log_out"
Именование drawable смотри в руководстве

2021-11-14 19:53 UTC, MegaR1CK commented on Ivan Saltykov/appyxa/app/src/main/res/layout/activity_profile.xml
> +            android:textSize="16dp"
Размер текста в sp

2021-11-15 21:00 UTC, Alexandr-Prokin requested changes
В остальных схожих элементах, сделай аналогичные правки

2021-11-16 21:27 UTC, Alexandr-Prokin requested changes

2021-11-16 21:27 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/res/values/strings.xml
> +    <string name="register_singin">Sing In</string>
siGN in

2021-11-16 21:27 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/res/values/strings.xml
> +    <string name="login_button">Sing In</string>
siGN in

2021-11-16 21:28 UTC, Alexandr-Prokin requested changes

2021-11-16 21:28 UTC, Alexandr-Prokin commented on Ivan Saltykov/appyxa/app/src/main/res/values/strings.xml
> +    <string name="login_singup">Sign Up</string>
siGN in

2021-11-17 18:10 UTC, Alexandr-Prokin approved these changes

2021-11-19 17:13 UTC, MegaR1CK approved these changes

2021-11-19 17:13 UTC, merged