Kosov Andrey L4
Student-MAD/android-homeworks pull request #20
Opened 2021-12-15 18:45 UTC by KosovAndrey

2021-12-17 08:21 UTC, MegaR1CK requested changes

2021-12-17 08:21 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Зачем?

2021-12-17 08:21 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_profile.xml
> +        />
На предыдущую строку

2021-12-17 08:21 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
не нужно

2021-12-17 08:30 UTC, MegaR1CK approved these changes

2021-12-29 16:57 UTC, Alexandr-Prokin approved these changes

2022-01-13 13:49 UTC, merged