Saltykov L7-8
Student-MAD/android-homeworks pull request #22
Opened 2022-01-19 15:24 UTC by IvanSaltykov

2022-01-19 16:57 UTC, MegaR1CK requested changes
1. У тулбара нет иконки для открытия боковой панели
2. При первом открытии панели не выбран ни один пункт

2022-01-21 05:44 UTC, MegaR1CK requested changes

2022-01-21 05:44 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/ProfileActivity.kt
> +            R.id.itemToolbarProfileMenu ->
Не, давай через специальную иконку drawer'а, как в уроке было

2022-02-01 19:36 UTC, Alexandr-Prokin approved these changes

2022-02-02 06:28 UTC, merged