Saltykov L9
Student-MAD/android-homeworks pull request #23
Opened 2022-02-02 16:28 UTC by IvanSaltykov

2022-02-10 06:37 UTC, MegaR1CK requested changes

2022-02-10 06:37 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/fragment_home_tasks_list.xml
> +        android:textSize="40dp"
В sp

2022-02-10 06:37 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/item_task.xml
> +                tools:text = "Name"
tools атрибуты в конце списка атрибутов

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/DatabaseTask.kt
> +        private const val NAME_TASK_COLUMN = "Name_Task"
Именование строчными и сущность не пишется после поля. Либо task_name, либо просто name
Второе относится и к модели Task
И к этому классу

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/DatabaseTask.kt
> +    fun getTask(): List<Task> {
Исходя из имени, ты получаешь одно задание, но тут список, переименуй метод

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/DatabaseTask.kt
> +                            nameTask = getString(getColumnIndexOrThrow("Name_Task")),
Имена колонок из констант

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/LoginActivity.kt
> +        if (preferences.login != "")
Есть соответствующие методы для этого

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/PreferencesManager.kt
> +        private const val NAME_PREFERENCES = "LoginAndPassword"
То же самое правило, сначала сущность, потом ее свойство

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/ProfileActivity.kt
> +                preferences.login = ""
Есть метод clear у преференсов, это в классе прописать отдельным методом

2022-02-10 06:37 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/TasksAdapter.kt
> +    fun submitList(times: List<Task>) {
Опечатка?

2022-02-11 20:03 UTC, MegaR1CK requested changes
При пометке задач выполненными/невыполненными изменения должны сохраняться
У аппбара на главной, если его свернуть, заголовок наезжает на кнопку меню

2022-03-10 06:24 UTC, MegaR1CK requested changes

2022-03-10 06:24 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/TaskViewHolder.kt
> +            listener.OnClick(position, task)
Позиция не всегда совпадает с id, например, если удалить задачу
Так что лучше будет добавить id в модель задачи, ты же можешь ее из бд получать
И передавать в листенер уже id

2022-03-10 06:24 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/TasksAdapter.kt
> +    interface Listener {
Слишком размыто, конкретнее

2022-03-10 06:24 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/TasksAdapter.kt
> +        fun OnClick(id: Int, task: Task)
И тут, и правила именования нарушены

2022-03-10 06:24 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +    lateinit var dataBaseTask: DatabaseTask
Может, приватными их сделать?

2022-03-18 19:41 UTC, MegaR1CK requested changes

2022-03-18 19:41 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/Task.kt
> +    var id: Int,
Почему тут что-то var, а что-то val? У тебя что-то изменяется?

2022-03-18 19:41 UTC, MegaR1CK commented on Ivan Saltykov/todoApp/app/src/main/java/com/example/todoapp/CategoryFragment.kt
> +    companion object {
Не надо в companion object, тогда переменные принадлежат всему классу в одном экземпляре, а тебе нужно, чтобы у каждого экземпляра класса были свои такие переменные, так что просто внутри класса делай

2022-03-18 19:46 UTC, MegaR1CK approved these changes

2022-03-18 20:11 UTC, Alexandr-Prokin approved these changes

2022-03-18 20:14 UTC, merged