Guznova-L6
Student-MAD/android-homeworks pull request #24
Opened 2022-02-14 19:45 UTC by NastenkaG

2022-02-17 10:48 UTC, MegaR1CK requested changes

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +            else -> PagerFragment(4)
Если PagerFragment только для этого, можно промто Frsgment создавать, этот код все равно никогда не выполнится
А PagerFragment удалить

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +            2 -> RecyclerViewWork()
Если в несколько ветвях одно и то же, можно объединить

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RecyclerViewWork.kt
> +class RecyclerViewWork : Fragment() {
Именование

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/TasksAdapter.kt
> +    fun addItems(task: Task) {
Почему во множественном числе?

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Task.kt
> +    val time: String
Время храним в LocalDateTime

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/item_task.xml
> +            android:layout_width="31dp"
Почему конкретные размеры?

2022-02-17 10:48 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/values/colors.xml
> +    <color name="time">#9F9F9F</color>
Что за цвет, непонятно

2022-02-19 18:21 UTC, NastenkaG commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +            2 -> RecyclerViewWork()
Я просто позже хочу создать для каждой странички разные списки, это я пока попробовать работает ли вообще

2022-02-19 18:25 UTC, NastenkaG commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Task.kt
> +    val time: String
Переменную так назвать? Просто я поменяла String на LocalDateTime и оно ругается

2022-02-19 18:29 UTC, NastenkaG commented on Anastasia Guznova/1proect/app/src/main/res/layout/item_task.xml
> +            android:layout_width="31dp"
Иначе слишком большой промежуток между CheckBox и текстом

2022-02-20 16:34 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +            else -> PagerFragment(4)
У тебя тут получается в пейджере PagerFragment, а в нем уже TasksWorkFragment, ненужная вроде вложенность

2022-02-20 16:35 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/MyPagerAdapter.kt
> +            2 -> RecyclerViewWork()
В таком случае тебе не нужно будет под каждый тип свой фрагмент создавать, просто передавать во фрагмент тип и исходя из типа получать определенные задачи

2022-02-20 16:35 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Task.kt
> +    val time: String
Ну так адаптируй) У LocalDateTime есть методы для перевода в строку и наоборот
В строку мы переводим только когда textView значение задаем

2022-02-24 10:21 UTC, MegaR1CK approved these changes

2022-02-24 11:46 UTC, Alexandr-Prokin approved these changes

2022-02-24 11:51 UTC, merged