Vlasenkova-L6
Student-MAD/android-homeworks pull request #28
Opened 2022-03-02 18:36 UTC by nastyavlass

2022-03-02 20:14 UTC, MegaR1CK requested changes
При нажатии на карточку задачи должен быть риппл и задача должна помечаться

2022-03-02 20:14 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerFragment.kt
> +                name = "Fkjldijlifdhh hfivhldfi vhldf hufvhdlfivhd " +
Что-то осмысленное?

2022-03-02 20:15 UTC, MegaR1CK requested changes

2022-03-02 20:15 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerFragment.kt
> +        val threeTasks = listOf(
Может логичнее передавать список задач во фрагмент, а все это генерировать в родительском? А то как-то не круто, что в одном фрагменте хранится вообще вся инфа для отображения

2022-03-02 21:12 UTC, nastyavlass commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerFragment.kt
> +        val threeTasks = listOf(
немного не поняла что откуда передавать и зачем(((

2022-03-03 09:09 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/PagerFragment.kt
> +        val threeTasks = listOf(
Это же у тебя дочерний фрагмент пейджера, которых три? Можно все это в родительском фрагменте объявлять, где с пейджером взаимодействие идет, и через конструктор передавать список

2022-03-03 14:43 UTC, MegaR1CK approved these changes

2022-03-03 17:58 UTC, Alexandr-Prokin approved these changes
Все ок

2022-03-03 17:59 UTC, merged