Kosov-L5
Student-MAD/android-homeworks pull request #29
Opened 2022-03-03 11:47 UTC by KosovAndrey

2022-03-03 17:49 UTC, Alexandr-Prokin reviewed
На экране профиля не сворачивается ничего
Нету табов на экране задач

Прочитай внимательно задание

2022-05-03 18:08 UTC, Alexandr-Prokin requested changes
![image](https://user-images.githubusercontent.com/35171601/166515399-e3ea8968-c73c-4941-974a-1f53f4551592.png)
Когда свернут, должен быть белым цветом.

Обрати внимание текст на кнопках, он капсом, нужно бы был без капса

2022-05-03 20:04 UTC, MegaR1CK requested changes
+ линт

2022-05-03 20:04 UTC, MegaR1CK commented on app/src/main/java/com/example/andreykosov/fragments/ProfileFragment.kt
> +        binding.CollapsingToolbarLayoutProfileFragment.title = getString(R.string.profile_greeting, name)
Именование id в xml в camelCase

2022-05-18 06:43 UTC, closed without merging