Vlasenkova-L3
Student-MAD/android-homeworks pull request #3
Opened 2021-10-27 19:30 UTC by nastyavlass

2021-11-01 18:21 UTC, MegaR1CK requested changes

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/HomeActivity.kt
> +import android.os.Bundle
Пустую строку везде между пакетом и импортами

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/MainActivity.kt
> +                    binding.editTextMainEmail.error = getString(R.string.email_error)
Для разных ошибок должны быть разные тексты, можно передавать в метод textInputLayout и там ставить ошибку, или из метода уже возвращать текст ошибку, тогда понадобится передать контекст, чтобы получить доступ к ресурсам

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/RegistrationActivity.kt
> +            val valid = Validation()
п. 5 руководства по неймингу

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_home.xml
> +        android:id="@+id/imageHomeFon"
Транслитерации запрещены (fon)

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="77dp"
высоту wrap content и подгони паддингами

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_registration.xml
> +        android:layout_height="85dp"
Аналогично

2021-11-01 18:21 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/values/strings.xml
> +    <string name="todo">picture</string>
Вместо todo поставь content_description например

2021-11-01 18:28 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_registration.xml
> +    <com.google.android.material.textfield.TextInputLayout
Поля не соответствуют дизайну

2021-11-01 18:29 UTC, MegaR1CK requested changes

2021-11-01 18:29 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_registration.xml
> +    <com.google.android.material.textfield.TextInputLayout
Поля не соответствуют дизайну

2021-11-08 19:05 UTC, MegaR1CK requested changes
![image](https://user-images.githubusercontent.com/51877618/140802180-92370e0c-235d-4f99-a4e1-92ce11588fbb.png)
У тебя в инпутах такая штука, задай input layout
style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"

2021-11-08 19:05 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/RegistrationActivity.kt
> +            if (valid.checkEmail(email) == null && valid.checkName(name) == null &&
Вместо того, чтобы вызывать метод по второму разу, можно проверять ошибки в инпутах

2021-11-08 19:05 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/RegistrationActivity.kt
> +            if (valid.checkEmail(email) == null && valid.checkName(name) == null &&
И второе условие на строке на след. строку

2021-11-08 19:05 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/Validator.kt
> +        if ((email.length < 6) or (!(email.contains("@"))))
можно использовать return if

2021-11-08 19:05 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/HomeActivity.kt
> +        binding.textHomeName.text = received
Нужно отображать Welcome, (email). Через строку с параметром

2021-11-09 16:51 UTC, MegaR1CK requested changes
![image](https://user-images.githubusercontent.com/51877618/140967912-a303fb0c-1086-4918-9ed2-71fd3ba8dc03.png)
некорректно отображается фон
![image](https://user-images.githubusercontent.com/51877618/140968051-3b522fde-77ee-415b-8c37-4d030af576f1.png)
если вызвать все ошибки, интерфейс еще едет, сверху отступ меньше, и на регистрации тоже

2021-11-09 16:51 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_main.xml
> +            android:hint="@string/main_pass_hint"
Неверный hint

2021-11-09 16:51 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.textfield.TextInputEditText
Пароль виден, используй inputType password

2021-11-09 16:51 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.textfield.TextInputEditText
На регистрации аналогично

2021-11-09 16:58 UTC, MegaR1CK requested changes

2021-11-09 16:58 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/Validator.kt
> +        return if (name.isEmpty())
Имя больше 4 символов

2021-11-09 20:11 UTC, MegaR1CK approved these changes

2021-11-10 10:26 UTC, Alexandr-Prokin approved these changes

2021-11-10 10:30 UTC, merged