GuznovaAnastasia
Student-MAD/android-homeworks pull request #4
Opened 2021-10-27 21:02 UTC by NastenkaG

2021-11-01 18:13 UTC, MegaR1CK requested changes

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/HomeActivity.kt
> +import android.os.Bundle
Везде пустую строку между пакетом и импортами, линт жаловаться не должен

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +    val valid = Validation()
Внутрь метода

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +        binding.regSignUp.setOnClickListener {
Это же вроде кнопка для перехода на логин?

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Validation.kt
> +class Validation {
Validator (п. 5 руководства по неймингу)

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Validation.kt
> +    fun validatePasswordRegistration(pass1: String, pass2: String): Boolean {
Не совсем корректное имя, а если сходство проверяется не только на регистрации?

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_home.xml
> +        android:id="@+id/profImageHumen"
Без humen можно

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +    >
На предыдущую строку, везде

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/logTextDontAcc"
лучше NoAcc

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_registration.xml
> +
Пустая строка

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_registration.xml
> +            android:id="@+id/textPassword1"
Непонятно, что за 1 и 2

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_slash.xml
> +        android:background="@drawable/startpeople"
start_image

2021-11-01 18:13 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/values/strings.xml
> +    <string name="welcome">Welcome Back!</string>
п. 9 руководства по неймингу

2021-11-01 18:26 UTC, MegaR1CK requested changes

2021-11-01 18:26 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Validation.kt
> +class Validation {
И для каждой ошибки (пустота, неправильный ввод) должен быть свой текст, можно возвращать из метода строку и ее ставить в ошибку. Но для этого понадобится передавать в метод (а можно и в класс) контекст для доступа к ресурсам

2021-11-03 19:24 UTC, MegaR1CK requested changes

2021-11-03 19:24 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +            val intent = Intent(this, HomeActivity::class.java)
Почему переход на Home?

2021-11-03 19:24 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/Validator.kt
> +        else return false
можно же просто возвращать логическое выражение, без true и false (return !(email.contains)...)

2021-11-03 19:27 UTC, MegaR1CK requested changes

2021-11-03 19:27 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +    <TextView
Нет отступа сверху

2021-11-03 19:27 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.textfield.TextInputLayout
Все поля ввода не соответствуют дизайну

2021-11-08 19:20 UTC, MegaR1CK requested changes
![image](https://user-images.githubusercontent.com/51877618/140804179-881e28dc-de22-4c33-9f70-e27c4af24b3b.png)
Интерфейс немного уехал (Pixel XL), попробуй уменьшить отступы

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +            if (valid.validateEmail(email) == null && valid.validatePassword(password) == null &&
Можно проверять состояние ошибок у полей, вместо вызова методов по второму разу

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/values/strings.xml
> +    <string name="error_emptiness">Поле пустое, введите текст)</string>
Скобочка

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/HomeActivity.kt
> +        binding.textViewName.text = userName
Через строку с параметром

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +            android:paddingStart="30sp"
paddingEnd тоже, студия просит

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.textfield.TextInputLayout
У всех инпутов рамку белую или прозрачную

2021-11-08 19:20 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +            binding.textEmailRegistration.error = valid.validateEmail(email)
Ошибки задаем TextInputLayout, а не EditText

2021-11-09 16:57 UTC, MegaR1CK requested changes
![image](https://user-images.githubusercontent.com/51877618/140969337-4005b908-7708-4a6c-9ea5-ac9d146ab3ba.png)
При ошибках едет интерфейс, еще меньше отступ сверху
Пароли должны скрываться, используй inputType = password на EditText
Неверный хинт в поле пароля на входе

2021-11-09 16:57 UTC, MegaR1CK commented on Anastasia Guznova/1proect/app/src/main/java/com/example/a1proect/RegistrationActivity.kt
> +            binding.regTextInputPasswordConfirm.error =
Имя тоже нужно валидировать

2021-11-11 17:37 UTC, MegaR1CK approved these changes

2021-11-11 17:42 UTC, Alexandr-Prokin approved these changes

2021-11-11 17:42 UTC, merged