Kosov-L3
Student-MAD/android-homeworks pull request #5
Opened 2021-10-28 19:59 UTC by KosovAndrey

2021-11-03 20:58 UTC, Alexandr-Prokin requested changes
По всем элементам интерфейса пройдись, нужно убрать точные размеры
// android:layout_width="350dp"
// android:layout_height="50dp"
 и сделать через margin

2021-11-03 20:58 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/signInActivity.kt
> +            if (!(emailValue.contains("@") && emailValue.length >= 7) && passwordValue.length >= 8)
Так и не убрал в класс

2021-11-03 20:58 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +        android:layout_width="273dp"
Точных значений не должно, нужно исправить везде, размеры задаются через margin

2021-11-03 20:58 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_register.xml
> +    <EditText
TextInputLayout + TextInputEditText вместо EditText

2021-11-03 21:13 UTC, Alexandr-Prokin requested changes
Пройдись по всем элементам интерфейса, и точные размеры убери, сделай через margin

2021-11-03 21:13 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +            when {
Так и не убрал проверку в класс

2021-11-03 21:13 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +        android:layout_width="273dp"
Точные размеры нужно убрать, сделать через margin

2021-11-08 19:28 UTC, MegaR1CK requested changes
На Pixel XL едет интерфейс, уменьши отступы
И приложение не собирается, косяки в манифесте

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +                (!(emailValue.contains("@") && emailValue.length >= 7) && passwordValue.length >= 8)
Логика в Validator, посмотри, как у других

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +                -> bindingClass.signInPassword.error = "Password must contain at least 8 characters"
Строки в ресурсы

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/Validator.kt
> +    fun validation(emailValue: String, passwordValue: String): Boolean {
Под каждое поле свой метод

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +         />
На предыдущую строку

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +        app:layout_constraintHorizontal_bias="0.497"
Биасы убрать

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_profile.xml
> +        android:backgroundTint="#FFD615"
Все цвета в верстке в ресурсы

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_sign_in.xml
> +    <EditText
Сделай относительную привязку к вью выше

2021-11-08 19:28 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/ProfileActivity.kt
> +class ProfileActivity : AppCompatActivity() {
Нужно передавать почту пользователя в активность и отображать через строку с параметром

2021-11-11 16:23 UTC, MegaR1CK requested changes
После правок зайди на экраны логина и регистрации и нажми кнопку ничего не заполняя. Если интерфейс будет уезжать под навбар, уменьши отступ сверху

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/ProfileActivity.kt
> +        binding.profileEmail.text = "Hello $userName"
Строку с параметром в ресурсы

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/RegisterActivity.kt
> +            if ((registerValidation.validateEmail(emailValue) == null) &&
Нужно выставить ошибки в поля textinputlayout

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +            binding.signInPasswordEditText.error = signInValidation.validatePassword(passwordValue)
Для корректного отображения ошибку задаем в textinputlayout

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +            if ((signInValidation.validateEmail(emailValue) == null) &&
Чтобы не прогонять методы 2 раза, можно считывать ошибку в инпуте

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/Validator.kt
> +class Validator(private val context: Context) {
Поле подтверждения пароля не валидируется на пустоту, имя пользователя тоже нужно валидировать

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +        android:id="@+id/getStartedUpImage"
Прочитай внимательнее п.2 руководства, сначала название элемента, потом название экрана

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_getstarted.xml
> +        android:id="@+id/getStartedUpImage"
Везде

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_profile.xml
> +        tools:text="Hello qwerty@gmail.com"
Tools атрибуты лучше в конец, после app атрибутов

2021-11-11 16:23 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_register.xml
> +            android:paddingStart="30sp"
В sp только размер текста, остальное в dp

2021-11-14 16:12 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +            val emailValue = binding.signInEmailEditText.text.toString()
ID к которому обращаешься, не существует, посмотри в активности

2021-11-14 16:12 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +            val passwordValue = binding.signInPasswordEditText.text.toString()
ID к которому обращаешься, не существует, посмотри в активности

2021-11-14 20:05 UTC, Alexandr-Prokin requested changes
![Screenshot_1636920200](https://user-images.githubusercontent.com/35171601/141696664-6d6d94a7-bd9e-4b4a-bb79-349b9c5055d0.png)

При пустых значения, и нажатию на кнопку регистр, переходит на следующий экран. Так не должно быть. На экран профиля не передает значения.

Синюю полоску сверху экрана нужно убрать, тогда не должно все так сдвигаться в кучу. Проверь все экраны на наложение объектов интерфейса

2021-11-15 17:23 UTC, MegaR1CK requested changes
Еще от меня, на скрине выше пароли не скрываются в точки, а должны

2021-11-19 17:46 UTC, Alexandr-Prokin requested changes
![image](https://user-images.githubusercontent.com/35171601/142667873-0bfe5340-5841-4a11-aa34-dfd794b9385e.png)
Сюда ничего не передается

2021-11-19 17:46 UTC, Alexandr-Prokin commented on Anastasia Guznova/1proect/app/src/main/res/layout/activity_registration.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
![image](https://user-images.githubusercontent.com/35171601/142666972-5387fe4a-003f-4401-a026-f22552765fbc.png)
можно еще ниже

2021-11-19 17:59 UTC, Alexandr-Prokin requested changes

2021-11-19 17:59 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_register.xml
> +            android:paddingStart="30sp"
В sp только размер текста, остальное в dp

2021-11-19 17:59 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/res/layout/activity_register.xml
> +            android:paddingStart="30sp"
В sp только размер текста, остальное в dp

2021-12-03 08:41 UTC, MegaR1CK requested changes
Неправильное именование некоторых id в xml, см. руководство

2021-12-03 08:41 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/RegisterActivity.kt
> +            with(binding) {
Тогда уж можно весь листенер в with обернуть, в нем везде binding используется

2021-12-03 08:41 UTC, MegaR1CK commented on Andrey Kosov/AndreyKosov/app/src/main/res/drawable/rounded_edittext.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android"
Можно удалить, если не используется

2021-12-07 17:48 UTC, MegaR1CK approved these changes

2021-12-08 21:28 UTC, Alexandr-Prokin commented on Andrey Kosov/AndreyKosov/app/src/main/java/com/example/andreykosov/SignInActivity.kt
> +                intent.putExtra("Name", emailValue)
intentProfile вместо intent

2021-12-10 07:41 UTC, Alexandr-Prokin approved these changes

2021-12-10 19:32 UTC, merged