StudentDaria/Add task 3
Student-MAD/android-homeworks pull request #6
Opened 2021-10-29 09:50 UTC by DariaHub

pr 1

2021-10-30 10:04 UTC, Alexandr-Prokin requested changes

2021-10-30 10:04 UTC, Alexandr-Prokin commented on Daria Pomelova/Pomelova - L3/app/src/main/res/layout/activity_login.xml
> +        android:hint="Confirm password"
выносится в ресурсы

2021-10-30 10:04 UTC, Alexandr-Prokin commented on Daria Pomelova/Pomelova - L3/app/src/main/res/layout/activity_login.xml
> +        android:text="Welcome Back!"
весь текст вынести в ресурсы

2021-12-02 16:40 UTC, Alexandr-Prokin approved these changes

2021-12-03 08:37 UTC, MegaR1CK requested changes
Неправильное именование id в xml, смотри руководство
Удали .idea из своей именной папки

2021-12-03 08:37 UTC, MegaR1CK commented on Daria Pomelova/L3/app/src/main/java/com/example/l3/Validator.kt
> +    fun validateIdenticalPassword(pass1: String, pass2: String): String? {
Давай по другому назовем, напр. password и confirmedPassword, а то непонятно

2021-12-10 19:29 UTC, MegaR1CK approved these changes

2021-12-10 19:29 UTC, merged