Churakov-L4
Student-MAD/android-homeworks pull request #8
Opened 2021-11-10 07:07 UTC by DyreLosh

Add fragments and navigation

2021-11-12 19:03 UTC, MegaR1CK requested changes

2021-11-12 19:03 UTC, MegaR1CK commented on Dinar Churakov/Churakov_L3/app/src/main/java/com/example/design_log/ProfileActivity.kt
> +            when (menuItem.itemId) {
Если везде возвращается true, то можно вынести его за when

2021-11-12 21:00 UTC, MegaR1CK approved these changes

2021-11-14 09:53 UTC, Alexandr-Prokin approved these changes

2021-11-14 10:05 UTC, merged