Vlasenkova-L4
Student-MAD/android-homeworks pull request #9
Opened 2021-11-14 16:56 UTC by nastyavlass

2021-11-26 09:09 UTC, MegaR1CK requested changes

2021-11-26 09:09 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/HomeActivity.kt
> +                    true
Возвращение true можно вынести за when, тут все ветви одно возвращают

2021-11-26 09:09 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/res/menu/bottom_navigation_home.xml
> +        android:id="@+id/menu_fragment_home_taskas_list"
camelCase + опечатка

2021-11-26 09:09 UTC, MegaR1CK commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/ProfileHomeFragment.kt
> +class ProfileHomeFragment() : Fragment() {
При пустом конструкторе твоего класса скобки необязательны

2021-11-28 19:17 UTC, nastyavlass commented on Anastasia Vlasenkova/git/app/src/main/java/com/example/myapplication/ProfileHomeFragment.kt
> +class ProfileHomeFragment() : Fragment() {
он ругается, если без них

2021-12-03 08:31 UTC, MegaR1CK approved these changes

2021-12-03 10:14 UTC, Alexandr-Prokin approved these changes

2021-12-04 10:54 UTC, merged